### PR TITLE
Fix for some function calls taking cint instead of int

### PR DESCRIPTION
**Pull request by idlewan**

### CODE REVIEW

**Comment by olwi** [comment]
@idlewan
Can you be more specific about your platform/compiler version?
Does the code actually not compile for you?
(Also, see the discussion here: https://forum.nim-lang.org/t/3340)

**Comment by idlewan** [comment]
Of course. I've read the forum thread, it's genuinely not compiling on my machine. I guess I'm as surprised as you are, I thought it wouldn't compile elsewhere either. Sorry for the original lack of details.

I'm on Archlinux 64bits, and my nim compiler is on devel from 7 days ago (6a6a2b7d76068e4c89a9b45d593def1f370464a1). I'll check with the nim stable compiler and devel-HEAD tomorrow.

**Comment by idlewan** [comment]
```fish
$> uname -a
Linux DesktopArch 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux
```
```fish
$> nim --version
Nim Compiler Version 0.17.2 (2017-09-11) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace

$> nimble prepare
       Info Hint: used config file '/etc/nim.cfg' [Conf]
     Error: Could not read package info file in /home/someone/gintro/gintro.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     usr/lib/nim/system/sysio.nim(192, 46) Error: type mismatch: got (int, File)
        ... but expected one of: 
        ... proc c_putc(c: cint; stream: File): cint
        ... .
```
```fish
$> nim --version
Nim Compiler Version 0.17.3 (2017-11-17) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: a11be5f21fc11d7aba3028213c77a984fb5594d6
active boot switches: -d:release

$> nimble prepare
  Executing task prepare in /home/someone/gintro/gintro.nimble
preparing gintro
Cloning into 'nim-glib'...
remote: Counting objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), done.
Cloning into 'nim-gobject'...
remote: Counting objects: 55, done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 55
Unpacking objects: 100% (55/55), done.
Cloning into 'nim-gir'...
remote: Counting objects: 31, done.
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 31
Unpacking objects: 100% (31/31), done.
Hint: used config file '/home/someone/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: gen [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: gir [Processing]
Hint: glib [Processing]
glib.nim(120, 40) Warning: expr is deprecated [Deprecated]
glib.nim(120, 47) Warning: expr is deprecated [Deprecated]
glib.nim(123, 40) Warning: expr is deprecated [Deprecated]
[...]
glib.nim(5262, 45) Warning: expr is deprecated [Deprecated]
glib.nim(5699, 49) Warning: expr is deprecated [Deprecated]
glib.nim(5699, 56) Warning: expr is deprecated [Deprecated]
glib.nim(2967, 3) Hint: 'G_NORMALIZE_NFKC' is declared but not used [XDeclaredButNotUsed]
glib.nim(31, 3) Hint: 'GTK_DOC_IGNORE' is declared but not used [XDeclaredButNotUsed]
glib.nim(34, 3) Hint: 'INC_STDLIB' is declared but not used [XDeclaredButNotUsed]
glib.nim(1865, 3) Hint: 'G_TRAVERSE_MASK' is declared but not used [XDeclaredButNotUsed]
glib.nim(26, 3) Hint: 'MINGW_H' is declared but not used [XDeclaredButNotUsed]
glib.nim(1866, 3) Hint: 'G_TRAVERSE_LEAFS' is declared but not used [XDeclaredButNotUsed]
glib.nim(23, 3) Hint: 'GLIB_COMPILATION' is declared but not used [XDeclaredButNotUsed]
glib.nim(2965, 3) Hint: 'G_NORMALIZE_NFC' is declared but not used [XDeclaredButNotUsed]
glib.nim(1867, 3) Hint: 'G_TRAVERSE_NON_LEAFS' is declared but not used [XDeclaredButNotUsed]
glib.nim(2964, 3) Hint: 'G_NORMALIZE_NFD' is declared but not used [XDeclaredButNotUsed]
glib.nim(22, 3) Hint: 'GLIB_H_INSIDE' is declared but not used [XDeclaredButNotUsed]
glib.nim(4131, 3) Hint: 'G_REGEX_MATCH_PARTIAL_SOFT' is declared but not used [XDeclaredButNotUsed]
glib.nim(3094, 3) Hint: 'G_IO_FLAGS_GET_MASK' is declared but not used [XDeclaredButNotUsed]
glib.nim(27, 3) Hint: 'STDLIB_H' is declared but not used [XDeclaredButNotUsed]
glib.nim(2966, 3) Hint: 'G_NORMALIZE_NFKD' is declared but not used [XDeclaredButNotUsed]
glib.nim(29, 3) Hint: 'MSC_VER' is declared but not used [XDeclaredButNotUsed]
Hint: gobject [Processing]
Hint: macros [Processing]
gobject.nim(27, 36) Warning: expr is deprecated [Deprecated]
gobject.nim(27, 43) Warning: expr is deprecated [Deprecated]
gobject.nim(40, 35) Warning: expr is deprecated [Deprecated]
[...]
gobject.nim(2553, 33) Warning: expr is deprecated [Deprecated]
gobject.nim(2555, 38) Warning: expr is deprecated [Deprecated]
gobject.nim(2557, 39) Warning: expr is deprecated [Deprecated]
gobject.nim(2560, 56) Error: ')' expected
stack trace: (most recent call last)
home/someone/gintro/gintro.nimble(63) prepareTask
home/someone/gintro/gintro.nimble(49) prep
home/someone/Nim/lib/system/nimscript.nim(215) exec
home/someone/Nim/lib/system/nimscript.nim(215, 7) Error: unhandled exception: FAILED: nim c gen.nim
```

**Comment by idlewan** [comment]
That should explain the pull request  that I made two days ago for the error using `devel` compiler:
`gobject.nim(2560, 56) Error: ')' expected`
https://github.com/ngtk3/nim-gobject/pull/1

With the fix for `gobject`, the compiler then gives errors with `cint` and `int`, thus this pull request to fix it.
If you need more details, don't hesitate to ask.

**Comment by StefanSalewski** [comment]
Problem was latest compiler.
Should work now again.

I will soon port bootstrapping away from deprecated ngtk3 to newer oldgtk3 package, that will give fever warnings.

**Comment by idlewan** [comment]
Thanks, tried with the latest commit in gintro and nim, works!

**Pull request closed without merging**
